/**
 * Artifact ID: QCQ-CMP-004
 * Artifact Name: ComposerManifest
 * Repository Path: QCQ/frontend/src/composer/ComposerManifest.ts
 */

import {
  COMPOSER_ARTIFACT_IDS,
  COMPOSER_BUILTIN_MODULE_IDS,
  COMPOSER_COMPATIBILITY_MINIMUM,
  COMPOSER_SCHEMA_VERSION,
  COMPOSER_VERSION,
} from './ComposerConstants';
import type {
  ComposerManifest,
  ComposerManifestEntry,
  ComposerModuleKind,
  ComposerRegistrationMode,
  ComposerZoneId,
} from './ComposerTypes';

interface ManifestEntryInput {
  readonly artifactId: string;
  readonly artifactName: string;
  readonly kind: ComposerModuleKind;
  readonly registration: ComposerRegistrationMode;
  readonly repositoryPath: string;
  readonly zone?: ComposerZoneId | null;
  readonly dependencies?: readonly string[];
  readonly required?: boolean;
  readonly description: string;
}

function entry(input: ManifestEntryInput): ComposerManifestEntry {
  return Object.freeze({
    artifactId: input.artifactId,
    artifactName: input.artifactName,
    version: COMPOSER_VERSION,
    kind: input.kind,
    registration: input.registration,
    repositoryPath: input.repositoryPath,
    zone: input.zone ?? null,
    dependencies: Object.freeze([...(input.dependencies ?? [])]),
    compatibility: Object.freeze({
      minimumVersion: COMPOSER_COMPATIBILITY_MINIMUM,
      maximumVersion: null,
    }),
    required: input.required ?? false,
    description: input.description,
  });
}

const ENTRIES: readonly ComposerManifestEntry[] = Object.freeze([
  entry({
    artifactId: 'QCQ-APP-001',
    artifactName: 'ApplicationShell',
    kind: 'application',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/app/ApplicationShell.tsx',
    dependencies: [],
    description: 'Application bootstrap and document-level shell authority.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.applicationLayout,
    artifactName: 'LayoutEngine',
    kind: 'application',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/app/LayoutEngine.tsx',
    dependencies: ['QCQ-APP-001'],
    required: true,
    description: 'Sole macro application-zone layout authority.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.tabletShell,
    artifactName: 'TabletApplicationShell',
    kind: 'component',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/tablet/TabletApplicationShell.tsx',
    zone: 'tablet',
    dependencies: [COMPOSER_BUILTIN_MODULE_IDS.applicationLayout],
    required: true,
    description: 'Semantic and visual tablet shell.',
  }),
  entry({
    artifactId: 'QCQ-TBL-002',
    artifactName: 'TabletLayoutEngine',
    kind: 'component',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/tablet/TabletLayoutEngine.tsx',
    zone: 'tablet',
    dependencies: [COMPOSER_BUILTIN_MODULE_IDS.tabletShell],
    description: 'Tablet-internal layout authority.',
  }),
  entry({
    artifactId: 'QCQ-TBL-003',
    artifactName: 'TabletViewport',
    kind: 'component',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/tablet/TabletViewport.tsx',
    zone: 'tablet',
    dependencies: ['QCQ-TBL-002'],
    description: 'Tablet scroll and content viewport.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.borderFrame,
    artifactName: 'BorderFrameEngine',
    kind: 'effect',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/frame/BorderFrameEngine.tsx',
    zone: 'tablet',
    dependencies: ['QCQ-TBL-003'],
    required: true,
    description: 'Composed metallic border and energy-frame system.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.questionTablet,
    artifactName: 'QuestionTablet',
    kind: 'component',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/tablet/QuestionTablet.tsx',
    zone: 'tablet',
    dependencies: ['QCQ-TBL-011', 'QCQ-TBL-012', 'QCQ-TBL-013', 'QCQ-TBL-014', 'QCQ-TBL-015'],
    required: true,
    description: 'Question, answer, counter, timer, and feedback composition.',
  }),

  entry({
    artifactId: 'QCQ-TBL-011',
    artifactName: 'QuestionViewport',
    kind: 'component',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/tablet/QuestionViewport.tsx',
    zone: 'tablet',
    dependencies: [],
    description: 'Long-content-safe question presentation viewport.',
  }),
  entry({
    artifactId: 'QCQ-TBL-012',
    artifactName: 'AnswerGrid',
    kind: 'component',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/tablet/AnswerGrid.tsx',
    zone: 'tablet',
    dependencies: ['QCQ-TBL-013'],
    description: 'Accessible single- and multiple-selection answer grid.',
  }),
  entry({
    artifactId: 'QCQ-TBL-013',
    artifactName: 'AnswerCard',
    kind: 'component',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/tablet/AnswerCard.tsx',
    zone: 'tablet',
    dependencies: [],
    description: 'Semantic answer control with keyboard, touch, and stylus behavior.',
  }),
  entry({
    artifactId: 'QCQ-TBL-014',
    artifactName: 'QuestionCounter',
    kind: 'component',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/tablet/QuestionCounter.tsx',
    zone: 'tablet',
    dependencies: [],
    description: 'Question position and completion progress indicator.',
  }),
  entry({
    artifactId: 'QCQ-TBL-015',
    artifactName: 'TimerDisplay',
    kind: 'component',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/tablet/TimerDisplay.tsx',
    zone: 'tablet',
    dependencies: [],
    description: 'Authoritative elapsed and remaining time presentation.',
  }),
  entry({
    artifactId: 'QCQ-TBL-016',
    artifactName: 'DatasetLoader',
    kind: 'service',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/dataset/DatasetLoader.ts',
    dependencies: [],
    description: 'Dataset loading and schema-validation boundary.',
  }),
  entry({
    artifactId: 'QCQ-TBL-017',
    artifactName: 'QuestionRegistry',
    kind: 'service',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/dataset/QuestionRegistry.ts',
    dependencies: ['QCQ-TBL-016'],
    description: 'Question identity, indexing, and lookup authority.',
  }),
  entry({
    artifactId: 'QCQ-TBL-018',
    artifactName: 'QuestionSessionEngine',
    kind: 'service',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/dataset/QuestionSessionEngine.ts',
    dependencies: ['QCQ-TBL-017'],
    description: 'Question-session state and ordering authority.',
  }),
  entry({
    artifactId: 'QCQ-TBL-019',
    artifactName: 'AnswerValidationEngine',
    kind: 'service',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/dataset/AnswerValidationEngine.ts',
    dependencies: ['QCQ-TBL-017'],
    description: 'Deterministic answer-validation authority.',
  }),
  entry({
    artifactId: 'QCQ-TBL-020',
    artifactName: 'QuestionProgressionEngine',
    kind: 'service',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/dataset/QuestionProgressionEngine.ts',
    dependencies: ['QCQ-TBL-018', 'QCQ-TBL-019'],
    description: 'Question progression and completion authority.',
  }),
  entry({
    artifactId: 'QCQ-TBL-021',
    artifactName: 'GameplayStore',
    kind: 'store',
    registration: 'registry',
    repositoryPath: 'QCQ/frontend/src/gameplay/GameplayStore.ts',
    dependencies: ['QCQ-TBL-018', 'QCQ-TBL-019', 'QCQ-TBL-020'],
    description: 'Authoritative gameplay state and evidence ledger.',
  }),
  entry({
    artifactId: 'QCQ-TBL-022',
    artifactName: 'ScoreEngine',
    kind: 'service',
    registration: 'registry',
    repositoryPath: 'QCQ/frontend/src/gameplay/ScoreEngine.ts',
    dependencies: ['QCQ-TBL-019'],
    description: 'Deterministic score authority.',
  }),
  entry({
    artifactId: 'QCQ-TBL-023',
    artifactName: 'XPManager',
    kind: 'service',
    registration: 'registry',
    repositoryPath: 'QCQ/frontend/src/gameplay/XPManager.ts',
    dependencies: ['QCQ-TBL-022'],
    description: 'Experience-point authority.',
  }),
  entry({
    artifactId: 'QCQ-TBL-024',
    artifactName: 'LevelEngine',
    kind: 'service',
    registration: 'registry',
    repositoryPath: 'QCQ/frontend/src/gameplay/LevelEngine.ts',
    dependencies: ['QCQ-TBL-023'],
    description: 'Level and rank progression authority.',
  }),
  entry({
    artifactId: 'QCQ-TBL-025',
    artifactName: 'AchievementEngine',
    kind: 'service',
    registration: 'registry',
    repositoryPath: 'QCQ/frontend/src/gameplay/AchievementEngine.ts',
    dependencies: ['QCQ-TBL-021', 'QCQ-TBL-023', 'QCQ-TBL-024'],
    description: 'Achievement evaluation authority.',
  }),
  entry({
    artifactId: 'QCQ-TBL-026',
    artifactName: 'MetricsStore',
    kind: 'store',
    registration: 'registry',
    repositoryPath: 'QCQ/frontend/src/metrics/MetricsStore.ts',
    dependencies: ['QCQ-TBL-021', 'QCQ-TBL-022'],
    description: 'Evidence-derived metrics authority.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.metricsPanel,
    artifactName: 'MetricsPanel',
    kind: 'component',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/metrics/MetricsPanel.tsx',
    zone: 'metrics',
    dependencies: ['QCQ-TBL-026'],
    required: true,
    description: 'Accessible metrics console.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.stormLayer,
    artifactName: 'StormLayer',
    kind: 'effect',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/effects/StormLayer.tsx',
    zone: 'environment',
    dependencies: ['QCQ-TBL-031', 'QCQ-TBL-032', 'QCQ-TBL-033'],
    required: true,
    description: 'Composite storm, lightning, and particle environment.',
  }),
  entry({
    artifactId: 'QCQ-TBL-031',
    artifactName: 'LightningLayer',
    kind: 'effect',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/effects/LightningLayer.tsx',
    zone: 'environment',
    dependencies: ['QCQ-TBL-033'],
    description: 'Procedural SVG lightning.',
  }),
  entry({
    artifactId: 'QCQ-TBL-032',
    artifactName: 'ParticleLayer',
    kind: 'effect',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/effects/ParticleLayer.tsx',
    zone: 'environment',
    dependencies: ['QCQ-TBL-033'],
    description: 'Canvas atmospheric particle field.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.glowEngine,
    artifactName: 'GlowEngine',
    kind: 'effect',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/effects/GlowEngine.ts',
    dependencies: [],
    description: 'Centralized glow computation and event authority.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.playerProfileStore,
    artifactName: 'PlayerProfileStore',
    kind: 'persistence',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/persistence/PlayerProfileStore.ts',
    dependencies: ['QCQ-PER-001', 'QCQ-PER-002', 'QCQ-PER-003', 'QCQ-PER-004', 'QCQ-PER-006', 'QCQ-PER-007', 'QCQ-PER-009'],
    description: 'Player identity, membership, preference, and metadata persistence.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.saveGameEngine,
    artifactName: 'SaveGameEngine',
    kind: 'persistence',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/persistence/SaveGameEngine.ts',
    dependencies: ['QCQ-PER-003', 'QCQ-PER-004', 'QCQ-PER-005', 'QCQ-PER-007', 'QCQ-PER-009'],
    description: 'Atomic save, restore, backup, and verification authority.',
  }),

  entry({
    artifactId: 'QCQ-PER-001',
    artifactName: 'PersistenceTypes',
    kind: 'persistence',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/persistence/PersistenceTypes.ts',
    dependencies: [],
    description: 'Immutable persistence contracts.',
  }),
  entry({
    artifactId: 'QCQ-PER-002',
    artifactName: 'PersistenceConstants',
    kind: 'persistence',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/persistence/PersistenceConstants.ts',
    dependencies: ['QCQ-PER-001'],
    description: 'Persistence keys, limits, versions, and defaults.',
  }),
  entry({
    artifactId: 'QCQ-PER-003',
    artifactName: 'PersistenceValidationEngine',
    kind: 'persistence',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/persistence/PersistenceValidationEngine.ts',
    dependencies: ['QCQ-PER-001', 'QCQ-PER-002'],
    description: 'Validation before save and after load.',
  }),
  entry({
    artifactId: 'QCQ-PER-004',
    artifactName: 'SerializationEngine',
    kind: 'persistence',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/persistence/SerializationEngine.ts',
    dependencies: ['QCQ-PER-001', 'QCQ-PER-002'],
    description: 'Canonical serialization and SHA-256 integrity.',
  }),
  entry({
    artifactId: 'QCQ-PER-005',
    artifactName: 'SessionRestoreEngine',
    kind: 'persistence',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/persistence/SessionRestoreEngine.ts',
    dependencies: ['QCQ-PER-003', 'QCQ-PER-004', 'QCQ-PER-006', 'QCQ-PER-007'],
    description: 'Primary and backup restoration orchestration.',
  }),
  entry({
    artifactId: 'QCQ-PER-006',
    artifactName: 'VersionMigrationEngine',
    kind: 'persistence',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/persistence/VersionMigrationEngine.ts',
    dependencies: ['QCQ-PER-001', 'QCQ-PER-004'],
    description: 'Forward schema migration graph.',
  }),
  entry({
    artifactId: 'QCQ-PER-007',
    artifactName: 'BackupRecoveryEngine',
    kind: 'persistence',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/persistence/BackupRecoveryEngine.ts',
    dependencies: ['QCQ-PER-001', 'QCQ-PER-002', 'QCQ-PER-004'],
    description: 'Checksummed rotating backups and recovery.',
  }),
  entry({
    artifactId: 'QCQ-PER-008',
    artifactName: 'PersistenceManifest',
    kind: 'persistence',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/persistence/PersistenceManifest.ts',
    dependencies: ['QCQ-PER-002'],
    description: 'Persistence subsystem ownership manifest.',
  }),
  entry({
    artifactId: 'QCQ-PER-009',
    artifactName: 'LocalStorageProvider',
    kind: 'persistence',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/persistence/LocalStorageProvider.ts',
    dependencies: ['QCQ-PER-001', 'QCQ-PER-002'],
    description: 'Staged local browser storage adapter.',
  }),
  entry({
    artifactId: 'QCQ-PER-010',
    artifactName: 'PlayerProgressSnapshot',
    kind: 'persistence',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/persistence/PlayerProgressSnapshot.ts',
    dependencies: ['QCQ-TBL-034', 'QCQ-TBL-035'],
    description: 'Immutable player progress projection.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.designTokens,
    artifactName: 'DesignTokens',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/DesignTokens.ts',
    dependencies: [],
    description: 'Primitive visual constitution.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.platinumFrameTheme,
    artifactName: 'PlatinumFrameTheme',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/PlatinumFrameTheme.ts',
    dependencies: ['QCQ-TBL-036', 'QCQ-THM-001', 'QCQ-THM-004'],
    description: 'Platinum frame material and depth authority.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.cyberEffects,
    artifactName: 'CyberEffects',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/CyberEffects.ts',
    dependencies: ['QCQ-THM-005', 'QCQ-THM-006'],
    description: 'Cyber-effect composition authority.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.energyAnimations,
    artifactName: 'EnergyAnimations',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/EnergyAnimations.ts',
    dependencies: ['QCQ-THM-007'],
    description: 'Energy-animation authority.',
  }),

  entry({
    artifactId: 'QCQ-THM-001',
    artifactName: 'ColorSystem',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/ColorSystem.ts',
    dependencies: ['QCQ-TBL-036'],
    description: 'Semantic, status, organization, and certification color authority.',
  }),
  entry({
    artifactId: 'QCQ-THM-002',
    artifactName: 'TypographySystem',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/TypographySystem.ts',
    dependencies: ['QCQ-TBL-036'],
    description: 'Fluid typography authority.',
  }),
  entry({
    artifactId: 'QCQ-THM-003',
    artifactName: 'SpacingSystem',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/SpacingSystem.ts',
    dependencies: ['QCQ-TBL-036'],
    description: 'Layout rhythm and spacing authority.',
  }),
  entry({
    artifactId: 'QCQ-THM-004',
    artifactName: 'ElevationSystem',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/ElevationSystem.ts',
    dependencies: ['QCQ-TBL-036'],
    description: 'Depth, shadow, z-index, and overlay authority.',
  }),
  entry({
    artifactId: 'QCQ-THM-005',
    artifactName: 'GlowProfiles',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/GlowProfiles.ts',
    dependencies: ['QCQ-TBL-036', 'QCQ-TBL-033'],
    description: 'Approved declarative glow profiles.',
  }),
  entry({
    artifactId: 'QCQ-THM-006',
    artifactName: 'ReflectionProfiles',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/ReflectionProfiles.ts',
    dependencies: ['QCQ-TBL-036', 'QCQ-TBL-033', 'QCQ-TBL-041'],
    description: 'Approved declarative reflection profiles.',
  }),
  entry({
    artifactId: 'QCQ-THM-007',
    artifactName: 'MotionProfiles',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/MotionProfiles.ts',
    dependencies: ['QCQ-TBL-036'],
    description: 'Motion and reduced-motion governance.',
  }),
  entry({
    artifactId: 'QCQ-THM-008',
    artifactName: 'AccessibilityTheme',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/AccessibilityTheme.ts',
    dependencies: ['QCQ-THM-001', 'QCQ-THM-002', 'QCQ-THM-007'],
    description: 'High-contrast, forced-colors, target-size, and text-scaling authority.',
  }),
  entry({
    artifactId: 'QCQ-THM-009',
    artifactName: 'VisualRegistry',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/VisualRegistry.ts',
    dependencies: [],
    description: 'Visual artifact registration and dependency ordering.',
  }),
  entry({
    artifactId: 'QCQ-THM-010',
    artifactName: 'ThemeManifest',
    kind: 'theme',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/styles/ThemeManifest.ts',
    dependencies: ['QCQ-TBL-036', 'QCQ-TBL-037', 'QCQ-TBL-038', 'QCQ-TBL-039', 'QCQ-THM-001', 'QCQ-THM-002', 'QCQ-THM-003', 'QCQ-THM-004', 'QCQ-THM-007', 'QCQ-THM-008', 'QCQ-THM-009'],
    description: 'Unified runtime theme manifest and compatibility authority.',
  }),
  entry({
    artifactId: COMPOSER_BUILTIN_MODULE_IDS.reflectionEngine,
    artifactName: 'ReflectionEngine',
    kind: 'effect',
    registration: 'external',
    repositoryPath: 'QCQ/frontend/src/effects/ReflectionEngine.ts',
    dependencies: ['QCQ-TBL-033'],
    description: 'Metallic, tablet, and environmental reflection computation.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.types,
    artifactName: 'ComposerTypes',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerTypes.ts',
    dependencies: [],
    required: true,
    description: 'Composition contracts.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.constants,
    artifactName: 'ComposerConstants',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerConstants.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.types],
    required: true,
    description: 'Composition identifiers and limits.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.config,
    artifactName: 'ComposerConfig',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerConfig.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.types, COMPOSER_ARTIFACT_IDS.constants],
    required: true,
    description: 'Runtime composition configuration authority.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.dependencyGraph,
    artifactName: 'ComposerDependencyGraph',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerDependencyGraph.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.types, COMPOSER_ARTIFACT_IDS.constants],
    required: true,
    description: 'Dependency control and cycle prevention.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.registry,
    artifactName: 'ComposerRegistry',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerRegistry.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.types, COMPOSER_ARTIFACT_IDS.constants, COMPOSER_ARTIFACT_IDS.dependencyGraph],
    required: true,
    description: 'Module discovery and registration authority.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.manifest,
    artifactName: 'ComposerManifest',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerManifest.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.types, COMPOSER_ARTIFACT_IDS.constants],
    required: true,
    description: 'Artifact registration manifest.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.validation,
    artifactName: 'ComposerValidationEngine',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerValidationEngine.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.manifest, COMPOSER_ARTIFACT_IDS.registry, COMPOSER_ARTIFACT_IDS.dependencyGraph],
    required: true,
    description: 'Composition validation authority.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.accessibility,
    artifactName: 'ComposerAccessibilityEngine',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerAccessibilityEngine.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.config],
    required: true,
    description: 'Application-wide accessibility orchestration.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.themeBridge,
    artifactName: 'ComposerThemeBridge',
    kind: 'theme',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerThemeBridge.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.accessibility, 'QCQ-THM-010'],
    required: true,
    description: 'Runtime visual-system bridge.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.persistenceBridge,
    artifactName: 'ComposerPersistenceBridge',
    kind: 'persistence',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerPersistenceBridge.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.config, COMPOSER_BUILTIN_MODULE_IDS.playerProfileStore, COMPOSER_BUILTIN_MODULE_IDS.saveGameEngine],
    required: true,
    description: 'Runtime profile, save, restore, migration, and backup bridge.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.lifecycle,
    artifactName: 'ComposerLifecycleEngine',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerLifecycleEngine.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.types, COMPOSER_ARTIFACT_IDS.constants],
    description: 'Composition lifecycle state authority.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.capabilityMatrix,
    artifactName: 'ComposerCapabilityMatrix',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerCapabilityMatrix.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.types, COMPOSER_ARTIFACT_IDS.constants],
    description: 'Evidence-driven composition capability authority.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.ownershipRegistry,
    artifactName: 'ComposerOwnershipRegistry',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerOwnershipRegistry.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.constants],
    description: 'Single-owner composition responsibility registry.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.policyEngine,
    artifactName: 'ComposerPolicyEngine',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerPolicyEngine.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.lifecycle, COMPOSER_ARTIFACT_IDS.capabilityMatrix, COMPOSER_ARTIFACT_IDS.ownershipRegistry],
    description: 'Composition policy authority.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.conflictResolver,
    artifactName: 'ComposerConflictResolver',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerConflictResolver.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.capabilityMatrix, COMPOSER_ARTIFACT_IDS.ownershipRegistry, COMPOSER_ARTIFACT_IDS.policyEngine],
    description: 'Ownership-preserving conflict resolution authority.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.readinessEvaluator,
    artifactName: 'ComposerReadinessEvaluator',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerReadinessEvaluator.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.lifecycle, COMPOSER_ARTIFACT_IDS.capabilityMatrix, COMPOSER_ARTIFACT_IDS.conflictResolver, COMPOSER_ARTIFACT_IDS.performanceProfile],
    description: 'Evidence-based composition readiness authority.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.certificationEngine,
    artifactName: 'ComposerCertificationEngine',
    kind: 'certification',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerCertificationEngine.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.readinessEvaluator, COMPOSER_ARTIFACT_IDS.validation],
    description: 'Evidence-backed composition certification authority.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.integrationEngine,
    artifactName: 'ComposerIntegrationEngine',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerIntegrationEngine.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.lifecycle, COMPOSER_ARTIFACT_IDS.capabilityMatrix, COMPOSER_ARTIFACT_IDS.ownershipRegistry, COMPOSER_ARTIFACT_IDS.policyEngine, COMPOSER_ARTIFACT_IDS.conflictResolver, COMPOSER_ARTIFACT_IDS.registry, COMPOSER_ARTIFACT_IDS.dependencyGraph],
    description: 'Cross-system integration orchestration authority.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.performanceProfile,
    artifactName: 'ComposerPerformanceProfile',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerPerformanceProfile.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.constants],
    description: 'Composition performance budget authority.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.qualityScaler,
    artifactName: 'ComposerQualityScaler',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerQualityScaler.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.performanceProfile, COMPOSER_ARTIFACT_IDS.capabilityMatrix, COMPOSER_ARTIFACT_IDS.accessibility],
    description: 'Adaptive rendering-cost scaling authority.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.monitoringBridge,
    artifactName: 'ComposerMonitoringBridge',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerMonitoringBridge.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.lifecycle, COMPOSER_ARTIFACT_IDS.capabilityMatrix],
    description: 'Non-owning monitoring integration bridge.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.telemetryBridge,
    artifactName: 'ComposerTelemetryBridge',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerTelemetryBridge.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.monitoringBridge],
    description: 'Privacy-bounded telemetry integration bridge.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.effectsBridge,
    artifactName: 'ComposerEffectsBridge',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerEffectsBridge.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.lifecycle, COMPOSER_ARTIFACT_IDS.qualityScaler, COMPOSER_ARTIFACT_IDS.themeBridge],
    description: 'Premium effects integration bridge.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.analyticsBridge,
    artifactName: 'ComposerAnalyticsBridge',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerAnalyticsBridge.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.lifecycle],
    description: 'Analytics integration bridge.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.aiBridge,
    artifactName: 'ComposerAIBridge',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerAIBridge.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.lifecycle],
    description: 'Assistive AI integration bridge.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.gamificationBridge,
    artifactName: 'ComposerGamificationBridge',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerGamificationBridge.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.lifecycle],
    description: 'Gamification integration bridge.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.leaderboardBridge,
    artifactName: 'ComposerLeaderboardBridge',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerLeaderboardBridge.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.lifecycle],
    description: 'Leaderboard integration bridge.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.organizationBridge,
    artifactName: 'ComposerOrganizationBridge',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerOrganizationBridge.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.lifecycle],
    description: 'Organization integration bridge.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.saasBridge,
    artifactName: 'ComposerSaaSBridge',
    kind: 'service',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerSaaSBridge.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.lifecycle],
    description: 'SaaS entitlement integration bridge.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.securityBridge,
    artifactName: 'ComposerSecurityBridge',
    kind: 'security',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/composer/ComposerSecurityBridge.ts',
    dependencies: [COMPOSER_ARTIFACT_IDS.lifecycle],
    description: 'Security posture and authorization bridge.',
  }),
  entry({
    artifactId: COMPOSER_ARTIFACT_IDS.master,
    artifactName: 'MasterTabletComposer',
    kind: 'application',
    registration: 'builtin',
    repositoryPath: 'QCQ/frontend/src/tablet/MasterTabletComposer.tsx',
    zone: 'tablet',
    dependencies: [
      COMPOSER_BUILTIN_MODULE_IDS.applicationLayout,
      COMPOSER_BUILTIN_MODULE_IDS.tabletShell,
      COMPOSER_BUILTIN_MODULE_IDS.borderFrame,
      COMPOSER_BUILTIN_MODULE_IDS.questionTablet,
      COMPOSER_BUILTIN_MODULE_IDS.metricsPanel,
      COMPOSER_BUILTIN_MODULE_IDS.stormLayer,
      COMPOSER_ARTIFACT_IDS.config,
      COMPOSER_ARTIFACT_IDS.manifest,
      COMPOSER_ARTIFACT_IDS.registry,
      COMPOSER_ARTIFACT_IDS.validation,
      COMPOSER_ARTIFACT_IDS.accessibility,
      COMPOSER_ARTIFACT_IDS.themeBridge,
      COMPOSER_ARTIFACT_IDS.persistenceBridge,
    ],
    required: true,
    description: 'Root tablet orchestration authority.',
  }),
]);

export const COMPOSER_MANIFEST: ComposerManifest = Object.freeze({
  schemaVersion: COMPOSER_SCHEMA_VERSION,
  composerVersion: COMPOSER_VERSION,
  entries: ENTRIES,
});

export function getComposerManifestEntry(
  artifactId: string,
  manifest: ComposerManifest = COMPOSER_MANIFEST,
): ComposerManifestEntry {
  const match = manifest.entries.find(
    (candidate) => candidate.artifactId === artifactId,
  );
  if (!match) {
    throw new Error(
      `Composer manifest does not contain artifact ${artifactId}.`,
    );
  }
  return match;
}

export function listComposerManifestEntries(
  options: {
    readonly zone?: ComposerZoneId;
    readonly requiredOnly?: boolean;
    readonly registration?: ComposerRegistrationMode;
  } = {},
  manifest: ComposerManifest = COMPOSER_MANIFEST,
): readonly ComposerManifestEntry[] {
  return Object.freeze(
    manifest.entries.filter((candidate) => {
      if (options.zone !== undefined && candidate.zone !== options.zone) {
        return false;
      }
      if (options.requiredOnly === true && !candidate.required) {
        return false;
      }
      if (
        options.registration !== undefined &&
        candidate.registration !== options.registration
      ) {
        return false;
      }
      return true;
    }),
  );
}
