export const SceneEvents = Object.freeze({
  ANSWER_SELECTED: 'quiz:answer-selected',
  ANSWER_CORRECT: 'quiz:answer-correct',
  ANSWER_INCORRECT: 'quiz:answer-incorrect',
  QUESTION_CHANGED: 'quiz:question-changed',
  STREAK_CHANGED: 'quiz:streak-changed',
  EXAM_STARTED: 'quiz:exam-started',
  EXAM_PAUSED: 'quiz:exam-paused',
  EXAM_RESUMED: 'quiz:exam-resumed',
  EXAM_COMPLETED: 'quiz:exam-completed',
  SESSION_RESTORED: 'quiz:session-restored',
  SCORE_REVEAL: 'quiz:score-reveal',
  DATASET_LOADED: 'quiz:dataset-loaded',
  DATASET_REJECTED: 'quiz:dataset-rejected',
  AUDIO_ENABLED: 'audio:enabled',
  AUDIO_MUTED: 'audio:muted',
  VISIBILITY_CHANGED: 'scene:visibility-changed',
});
